### ISSUE TITLE
Busted code embeds

### ISSUE THREAD

**Issue by genehack** [yanick/blog_entries#4]
All the code embeds in https://techblog.babyl.ca/entry/vue-docs/ are just showing this:

<img width="932" alt="Screen Shot 2020-10-27 at 07 45 29" src="https://user-images.githubusercontent.com/42126/97317777-63f9b600-1828-11eb-8830-aa1a41d39f96.png">

**Comment by yanick** [comment]
One  rewrite later, it works once more! (or should)
